spring:
  profiles:
    active: docker
  resources:
    chain:
      cache: false
fido2:
  rp:
    id: bjxavbbc7tbb.ddns.net
    origin: bjxavbbc7tbb.ddns.net
    port: 
conformance:
  url: https://bjxavbbc7tbb.ddns.net
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    com.linecorp.line: DEBUG
fido2-server:
  host: fido2

